## Vectorization

In [34]:
import numpy as np

### Single vector operations

In [35]:
a=np.array([1,2,3,4])
print(f"a:  {a}")

# neget elements of a
b=-a
print(f"b=-a:   {b}")

# Sum all elements of a returns scaler
b=np.sum(a)
print(f"np.sum(a):  {b}")

b=np.mean(a)
print(f"np.mean(a):  {b}")

b=a**2
print(f"a**2:  {b}")

a:  [1 2 3 4]
b=-a:   [-1 -2 -3 -4]
np.sum(a):  10
np.mean(a):  2.5
a**2:  [ 1  4  9 16]


### Vector Vector element-wise operations 

In [36]:
a=np.array([1,2,3,4])  
b=np.array([-1,-2,3,4])

print(f"a+b = {a+b}")

a+b = [0 0 6 8]


Vetors must be of the same size

In [37]:
c=np.array([6,7])

try:
    d=b+c
except Exception as e:
    print(f"The eror is: {e}")

The eror is: operands could not be broadcast together with shapes (4,) (2,) 


### Scalar vector operations

In [38]:
# Multiply a by a scalar
b=5*a
print(f"5 * a: {b}")

5 * a: [ 5 10 15 20]


### Vector vector dot product

In [39]:
a=np.array([1,2,3,4])
b=np.array([1,2,3,4])
c=np.dot(a,b)

print(f"dot product is: {c}")

dot product is: 30


### Vector vs for loop

In [40]:
import time
# Setting the seed makes the sequence of random numbers deterministic — 
# meaning, you'll get the same sequence of numbers every time you run the code.
# use any integer value (like 0, 42, 123, etc.). Each seed value gives a 
# different repeatable sequence of "random" numbers.
np.random.seed(1)

a=np.random.rand(10000000)
b=np.random.rand(10000000)

# using for loop
dot=0
tic=time.time() # Get start time
for i in range(a.shape[0]):
    dot+=a[i]*b[i]
toc=time.time() # get end time

print(f"Using for loop the dot product is: {dot:.4f} and duration: {1000*(toc-tic):.4f} ms")

# Using vector operation
tic=time.time() # Get start time
dot=np.dot(a,b)
toc=time.time() # get end time

print(f"Using vector operation the dot product is: {dot:.4f} and duration: {1000*(toc-tic):.4f} ms")

# Remove these big arrays from memory
del(a)
del(b)

Using for loop the dot product is: 2501072.5817 and duration: 7430.4335 ms
Using vector operation the dot product is: 2501072.5817 and duration: 0.0000 ms


## Matrices

### Matrix creation

In [41]:
a=np.zeros((1,5))
print(f"Shape of a: {a.shape}, a={a}")

a=np.zeros((2,1))
print(f"Shape of a: {a.shape}, a={a}")

a=np.random.random_sample((2,3))
print(f"Shape of a: {a.shape}, a={a}")

Shape of a: (1, 5), a=[[0. 0. 0. 0. 0.]]
Shape of a: (2, 1), a=[[0.]
 [0.]]
Shape of a: (2, 3), a=[[0.44236513 0.04997798 0.77390955]
 [0.93782363 0.5792328  0.53516563]]


Create manually

In [42]:
a=np.array([[3],
            [2],
            [1]])
print(f"Shape of a: {a.shape}, a={a}")

Shape of a: (3, 1), a=[[3]
 [2]
 [1]]


### Matrix Indexing

In [43]:
a=np.arange(6).reshape(-1,2) # Column specified, row will be calculated
print(f"a.shape: {a.shape}, \ta= {a}")

#access an element
print(f"a[2,0].shape: {a[2,0].shape}, \ta[2,0]= {a[2,0]}")

#access a row
print(f"a[2].shape: {a[2].shape}, \ta[2]= {a[2]}")

a.shape: (3, 2), 	a= [[0 1]
 [2 3]
 [4 5]]
a[2,0].shape: (), 	a[2,0]= 4
a[2].shape: (2,), 	a[2]= [4 5]


### Matrix Slicing

In [44]:
# Vector 2D slicing operations
a=np.arange(20).reshape(-1,10)
print(f"a= {a}")

# start:stop:step
# Acces 5 consecutive elements from first row
print(f"a[0, 2:7:1] = {a[0,2:7:1]}, \ta[0, 2:7:1].shape= {a[0, 2:7:1].shape}")
# Acces 5 consecutive elements from second row
print(f"a[1, 2:7:1] = {a[1,2:7:1]}, \ta[1, 2:7:1].shape= {a[1, 2:7:1].shape}")

# Access all elemts
print(f"a[:,:] = {a[:,:]}, \ta[:,:].shape= {a[:,:].shape}")

# Access all elements of a single row
print(f"a[1,:] = {a[1,:]}, \ta[1,:].shape= {a[1,:].shape}")
# same as
print(f"a[1] = {a[1]}, \ta[1].shape= {a[1].shape}")

a= [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
a[0, 2:7:1] = [2 3 4 5 6], 	a[0, 2:7:1].shape= (5,)
a[1, 2:7:1] = [12 13 14 15 16], 	a[1, 2:7:1].shape= (5,)
a[:,:] = [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]], 	a[:,:].shape= (2, 10)
a[1,:] = [10 11 12 13 14 15 16 17 18 19], 	a[1,:].shape= (10,)
a[1] = [10 11 12 13 14 15 16 17 18 19], 	a[1].shape= (10,)
